Repository boostcampwm-2021/Web11-Donggle, pull requests merged in 2021-11, with the labels that each got.

#9 [feat/react_structure] 리액트 구조 초기 설정
  client/package.json
  client/src/App.tsx
  client/src/components/Header/index.tsx
  client/src/components/TempCounter.tsx
  client/src/components/index.ts
  client/src/pages/MainPage.tsx
  client/src/pages/NotFoundPage.tsx
  client/src/pages/index.ts
  client/src/stores/GlobalStore.tsx
  client/src/stores/atoms.ts
  client/src/stores/index.ts
  client/yarn.lock
Labels: Feat, FE, High

#12 [feat/global_style]GlobalStyle 적용
  client/src/App.tsx
  client/src/styledComponents/index.ts
Labels: Fix, Chore, FE, High

#16 [Feat/login_layout] 로그인 모달 적용 및 내부 버튼 구현
  client/src/assets/icons/facebook.svg
  client/src/assets/icons/google.svg
  client/src/assets/icons/naver.svg
  client/src/components/LoginPlate/index.style.tsx
  client/src/components/LoginPlate/index.tsx
  client/src/components/modal/index.style.tsx
  client/src/components/modal/index.tsx
Labels: Feat, FE

#22 [Feat] Map 렌더링 및 폴리곤 생성
  .gitignore
  client/package.json
  client/public/index.html
  client/src/components/Map/data.tsx
  client/src/components/Map/index.style.tsx
  client/src/components/Map/index.tsx
  client/src/components/Map/jongro.json
  client/src/pages/MainPage.tsx
  client/src/styledComponents/GlobalStyle.ts
  client/tsconfig.json
  client/yarn.lock
Labels: Feat, FE, High

#24 [Feat] MAP 정보 DB 저장 및 기본 Polygon 생성
  .gitignore
  server/.env
  server/package.json
  server/src/api/admin.ts
  server/src/api/index.ts
  server/src/app.ts
  server/src/loaders/dbLoader.ts
  server/src/loaders/expressLoader.ts
  server/src/loaders/index.ts
  server/src/models/Map.ts
  server/src/models/index.ts
  server/src/services/updateMap.ts
  server/yarn.lock
Labels: Feat, FE, High

#27 Feat/map polygon api
  server/src/api/admin.ts
  server/src/api/index.ts
  server/src/api/map.ts
  server/src/models/Map.ts
  server/src/services/map.ts
  server/src/services/updateMap.ts
  server/yarn.lock
Labels: Feat, Fix, BE, High

#28 Feat: #26 맵 중심 좌표, 축척 정보 기반 폴리곤 API 요청 코드 구현
  client/.env
  client/src/components/Map/data.tsx
  client/src/components/Map/index.tsx
  client/src/components/Map/jongro.json
  client/src/controllers/mapController.ts
  client/tsconfig.json
  client/tsconfig.path.json
Labels: Feat, FE, High

#30 [Fix] Front - Back 폴리곤 좌표 fetch 및 그리기 테스트 완료
  client/src/components/Map/index.tsx
  client/src/controllers/mapController.ts
  server/.env
  server/package.json
  server/src/api/map.ts
  server/src/loaders/expressLoader.ts
  server/src/services/map.ts
  server/src/services/updateMap.ts
  server/yarn.lock
Labels: Fix, Refactor, BE, FE, High

#34 Fix/polygon 구멍, 멀티 폴리곤 수정
  client/src/components/Map/index.tsx
  client/src/controllers/mapController.ts
  server/src/models/Map.ts
  server/src/services/mapService.ts
  server/src/services/updateMapService.ts
Labels: Fix, BE, FE, High

#42 [Feat/marker] Map API 활용한 커스텀 마커 띄우기 + 폴리곤 fetch 중복요청 수정
  client/src/components/Map/index.tsx
  client/src/controllers/mapController.ts
  client/src/controllers/markerController.ts
  client/src/utils/marker.ts
Labels: Feat, Fix, FE, High

#40 Feat/polygon speed 폴리곤 최적화
  client/src/components/Map/index.tsx
  client/src/controllers/mapController.ts
  server/.env
  server/src/api/adminController.ts
  server/src/models/Map.ts
  server/src/services/updateMapService.ts
Labels: Feat, Fix, BE, FE, High

#47 [Feat] 축척 수준에 따른 행정구역 중앙 마커 표시
  client/src/assets/images/vertex_white.png
  client/src/components/Map/index.tsx
  client/src/components/Map/markerStyle.css
  client/src/controllers/mapController.ts
  client/src/controllers/markerController.ts
  client/src/utils/address.ts
  client/src/utils/marker.ts
  server/package.json
  server/yarn.lock
Labels: Feat, Design, FE, 리뷰요청, High

#46 [Feat/map_search] 검색 기능 구형
  client/src/assets/icons/search.svg
  client/src/components/Map/index.tsx
  client/src/components/Searchbar/index.style.tsx
  client/src/components/Searchbar/index.tsx
  client/src/controllers/searchbarController.ts
  server/src/api/adminController.ts
  server/src/api/mapController.ts
  server/src/models/SimpleMap.ts
  server/src/services/index.ts
  server/src/services/mapService.ts
  server/src/services/updateMapService.ts
Labels: Feat, Fix, BE, FE, High

#49 [Feat] : 헤더 UI 개선 및 Sidebar 기본 UI 구현
  client/.env
  client/package.json
  client/src/App.tsx
  client/src/components/Header/index.style.tsx
  client/src/components/Header/index.tsx
  client/src/components/Map/index.style.tsx
  client/src/components/Map/index.tsx
  client/src/components/Sidebar/index.style.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/modal/index.style.tsx
  client/src/components/modal/index.tsx
  client/src/controllers/mapController.ts
  client/src/index.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/RankingPage.tsx
  client/src/pages/ReviewPage.tsx
  client/src/pages/index.ts
  client/src/styledComponents/theme.ts
  client/yarn.lock
  server/.env
Labels: Feat, Fix, FE, High

#48 Deploy/server [#43] 서버 nginx와 github action 배포
  .github/workflows/main.yml
  client/.env
  client/src/controllers/mapController.ts
  client/src/controllers/searchbarController.ts
  server/package.json
  server/src/loaders/expressLoader.ts
Labels: Deploy, High

#56 [Feat/db design] DB 스키마 변경 적용
  client/src/components/Searchbar/index.tsx
  client/src/controllers/mapController.ts
  client/src/controllers/markerController.ts
  client/src/controllers/searchbarController.ts
  server/src/api/adminController.ts
  server/src/models/Map.ts
  server/src/models/MapInfo.ts
  server/src/models/SimpleMap.ts
  server/src/services/mapService.ts
  server/src/services/updateMapService.ts
Labels: Fix, BE, FE, High

#64 [fix/except_region] 예외 도시 처리
  server/src/services/mapService.ts
Labels: Fix, BE, Middle

#66 [Feat] Sidebar 기본 UI 구현 완료 및 Main Page 불 필요 코드 제거
  client/src/components/Common/BarRate/index.style.tsx
  client/src/components/Common/BarRate/index.tsx
  client/src/components/Common/HashTag/index.style.tsx
  client/src/components/Common/HashTag/index.tsx
  client/src/components/Common/StarRate/index.style.tsx
  client/src/components/Common/StarRate/index.tsx
  client/src/components/Sidebar/index.style.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/TempCounter.tsx
  client/src/components/index.ts
  client/src/pages/MainPage.tsx
  client/src/stores/atoms.ts
  client/src/styledComponents/theme.ts
Labels: Feat, Fix, FE, Middle

#68 [Feat] 마커 클릭시 사이드바 렌더링
  client/src/components/Map/index.tsx
  client/src/components/Map/markerStyle.css
  client/src/components/Sidebar/index.style.tsx
  client/src/components/Sidebar/index.tsx
  client/src/controllers/markerController.ts
  client/src/pages/MainPage.tsx
  package.json
  server/src/api/mapController.ts
  yarn.lock
Labels: Feat, Fix, FE, High

#70 [Deploy] dev -> main 반영 (2021-11-11)
  .github/workflows/main.yml
  client/src/App.tsx
  client/src/assets/icons/marker.svg
  client/src/components/Common/BarRate/index.style.tsx
  client/src/components/Common/BarRate/index.tsx
  client/src/components/Common/HashTag/index.style.tsx
  client/src/components/Common/HashTag/index.tsx
  client/src/components/Common/StarRate/index.style.tsx
  client/src/components/Common/StarRate/index.tsx
  client/src/components/Map/index.style.tsx
  client/src/components/Map/index.tsx
  client/src/components/Map/markerStyle.css
  client/src/components/Searchbar/index.tsx
  client/src/components/Sidebar/index.style.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/TempCounter.tsx
  client/src/components/index.ts
  client/src/controllers/mapController.ts
  client/src/controllers/markerController.ts
  client/src/controllers/searchbarController.ts
  client/src/pages/MainPage.tsx
  client/src/stores/atoms.ts
  client/src/styledComponents/theme.ts
  package.json
  server/ecosystem.config.js
  server/package.json
  server/src/api/adminController.ts
  server/src/api/mapController.ts
  server/src/models/Map.ts
  server/src/models/MapInfo.ts
  server/src/models/SimpleMap.ts
  server/src/services/mapService.ts
  server/src/services/updateMapService.ts
  yarn.lock
Labels: Deploy

#73 [Fix] Node.js CD 오류 해결
  client/package.json
  client/yarn.lock
  package.json
  yarn.lock
Labels: Fix, Deploy

#74 [Deploy] CD 오류 해결
  client/package.json
  client/yarn.lock
  package.json
  yarn.lock
Labels: Deploy

#81 [Feat] 폴리곤 클릭시 해당 지역 사이드바 열기
  client/src/components/Map/index.tsx
  client/src/controllers/mapController.ts
  client/src/controllers/markerController.ts
  server/ecosystem.config.js
  server/src/api/adminController.ts
  server/src/api/mapController.ts
  server/src/services/mapService.ts
  server/src/services/updateMapService.ts
Labels: Feat, FE, Low

#82 [Feat] 후기 작성 Backend API 구현
  client/package.json
  client/src/App.tsx
  client/src/components/Common/BarRate/index.tsx
  client/src/components/Common/DynamicStarRate/index.style.tsx
  client/src/components/Common/DynamicStarRate/index.tsx
  client/src/components/Common/HashTag/index.tsx
  client/src/components/Common/StarRate/index.tsx
  client/src/components/Header/index.tsx
  client/src/components/ReviewModal/index.style.tsx
  client/src/components/ReviewModal/index.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/modal/index.style.tsx
  client/src/components/modal/index.tsx
  client/src/controllers/reviewController.ts
  client/src/pages/MainPage.tsx
  client/src/utils/enum.ts
  client/src/utils/type.d.ts
  client/yarn.lock
  server/src/api/reviewController.ts
  server/src/loaders/expressLoader.ts
  server/src/models/Review.ts
  server/src/services/index.ts
  server/src/services/reviewService.ts
  server/src/utils/type.d.ts
Labels: Feat, BE, High

#91 Feat/profile page 프로필 페이지 구현
  client/src/App.tsx
  client/src/components/AddressModal/index.style.tsx
  client/src/components/AddressModal/index.tsx
  client/src/components/Header/index.style.tsx
  client/src/components/Header/index.tsx
  client/src/components/Map/index.style.tsx
  client/src/components/Map/index.tsx
  client/src/components/Profile/index.style.tsx
  client/src/components/Profile/index.tsx
  client/src/components/ReviewModal/index.tsx
  client/src/components/Searchbar/index.style.tsx
  client/src/components/Searchbar/index.tsx
  client/src/components/Searchbar/signIn.tsx
  client/src/components/SignInModal/index.tsx
  client/src/components/SignUpModal/index.style.tsx
  client/src/components/SignUpModal/index.tsx
  client/src/components/modal/index.style.tsx
  client/src/components/modal/index.tsx
  client/src/controllers/profileController.ts
  client/src/controllers/searchbarController.ts
  client/src/pages/MainPage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/pages/RankingPage.tsx
  client/src/pages/ReviewPage.tsx
  client/src/pages/SignUpPage.tsx
  client/src/pages/index.ts
  client/src/stores/atoms.ts
  client/src/styledComponents/GlobalStyle.ts
  client/src/utils/type.d.ts
  server/package.json
  server/src/api/authController.ts
  server/src/api/indexController.ts
  server/src/api/userController.ts
  server/src/app.ts
  server/src/models/User.ts
  server/src/services/index.ts
  server/src/services/userService.ts
  server/yarn.lock
Labels: Feat, Fix, BE, FE, High

#97 [Refactor] DB Schema 일부 변경 및 Refactoring
  client/src/components/AddressModal/index.tsx
  client/src/components/Common/BarRate/index.tsx
  client/src/components/Common/DynamicStarRate/index.tsx
  client/src/components/Common/Modal/index.style.tsx
  client/src/components/Common/Modal/index.tsx
  client/src/components/Map/index.style.tsx
  client/src/components/Map/index.tsx
  client/src/components/ReviewModal/index.tsx
  client/src/components/Searchbar/index.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/SignInModal/index.tsx
  client/src/controllers/mapController.ts
  client/src/controllers/markerController.ts
  client/src/controllers/profileController.ts
  client/src/controllers/searchbarController.ts
  client/src/hooks/useHistoryRouter.ts
  client/src/pages/LoadingPage.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/RankingPage.tsx
  client/src/types/Common.d.ts
  client/src/types/Map.d.ts
  client/src/types/Review.d.ts
  client/src/utils/common.ts
  client/src/utils/type.d.ts
  client/tsconfig.path.json
  server/src/api/mapController.ts
  server/src/models/MapInfo.ts
  server/src/models/Review.ts
  server/src/services/mapService.ts
  server/src/services/updateMapService.ts
Labels: Refactor, BE, FE, High

#98 Feat/profile page 구현 완료
  client/src/App.tsx
  client/src/assets/icons/x.svg
  client/src/components/AddressModal/index.style.tsx
  client/src/components/AddressModal/index.tsx
  client/src/components/Common/Modal/index.style.tsx
  client/src/components/Common/Modal/index.tsx
  client/src/components/Profile/index.tsx
  client/src/components/Searchbar/index.tsx
  client/src/controllers/profileController.ts
  client/src/controllers/searchbarController.ts
  client/src/hooks/useHistoryRouter.ts
  client/src/pages/ProfileAddressPage.tsx
  client/src/pages/index.ts
  server/src/api/mapController.ts
  server/src/api/userController.ts
  server/src/services/mapService.ts
  server/src/services/userService.ts
Labels: Feat, BE, FE, High

#104 Feat/profile page 스타일 수정
  client/src/App.tsx
  client/src/components/AddressModal/index.style.tsx
  client/src/components/Common/Modal/index.style.tsx
  client/src/components/Searchbar/index.style.tsx
  client/src/components/Searchbar/index.tsx
Labels: Fix, FE, Middle

#111 [Feat] 랭킹 페이지 구현
  client/.env
  client/src/assets/icons/ranking.svg
  client/src/components/Common/CircleRate/index.tsx
  client/src/components/Map/index.tsx
  client/src/components/RankingModal/Rankbar/index.style.tsx
  client/src/components/RankingModal/Rankbar/index.tsx
  client/src/components/RankingModal/Selector/index.style.tsx
  client/src/components/RankingModal/Selector/index.tsx
  client/src/components/RankingModal/index.style.tsx
  client/src/components/RankingModal/index.tsx
  client/src/controllers/rankController.ts
  client/src/pages/RankingPage.tsx
  client/src/styledComponents/theme.ts
  client/src/types/Rank.d.ts
  client/src/utils/common.ts
  server/.env
  server/src/api/indexController.ts
  server/src/api/rankController.ts
  server/src/services/index.ts
  server/src/services/mapService.ts
  server/src/services/rankService.ts
Labels: Feat, BE, FE, Middle

#107 Feat/search debounce 검색바 디바운스 구현
  client/src/components/Searchbar/index.tsx
  client/src/utils/common.ts
Labels: Feat, FE, Middle

#106 Feat/error snackbar 스낵바 구현
  client/src/App.tsx
  client/src/components/Sidebar/index.tsx
  client/src/components/Snackbar/index.style.tsx
  client/src/components/Snackbar/index.tsx
  client/src/controllers/reviewController.ts
  client/src/index.tsx
  client/src/styledComponents/theme.ts
  client/src/types/Common.d.ts
  client/src/utils/common.ts
  client/src/utils/index.ts
  server/src/api/userController.ts
Labels: Feat, FE, Low

#112 [Feat] 사이드바 리뷰 기능 구현
  client/src/App.tsx
  client/src/components/Common/BarRate/index.tsx
  client/src/components/Common/DetailBtn/index.style.tsx
  client/src/components/Common/DetailBtn/index.tsx
  client/src/components/Common/ReviewContent/index.style.tsx
  client/src/components/Common/ReviewContent/index.tsx
  client/src/components/Header/index.style.tsx
  client/src/components/Header/index.tsx
  client/src/components/Map/index.style.tsx
  client/src/components/ReviewModal/index.tsx
  client/src/components/Sidebar/index.style.tsx
  client/src/components/Sidebar/index.tsx
  client/src/controllers/reviewController.ts
  client/src/controllers/sidebarController.ts
  client/src/pages/MainPage.tsx
  client/src/pages/ReviewPage.tsx
  client/src/pages/ReviewSubmitPage.tsx
  client/src/pages/index.ts
  client/src/styledComponents/theme.ts
  client/src/types/Review.d.ts
  server/src/api/reviewController.ts
  server/src/models/Review.ts
  server/src/services/mapService.ts
  server/src/services/reviewService.ts
  server/src/types/Review.d.ts
Labels: Feat, Fix, BE, FE, High

#123 [Feat] 후기 제출 시 로그인 유효성 검증 관련 로직 적용
  client/src/App.tsx
  client/src/components/Common/Modal/index.tsx
  client/src/components/Common/ReviewContent/index.tsx
  client/src/components/ReviewModal/index.tsx
  client/src/controllers/reviewController.ts
  client/src/types/Review.d.ts
  server/src/api/reviewController.ts
  server/src/middlewares/auth.ts
  server/src/models/Review.ts
Labels: Feat, Fix, BE, FE, High

#132 [Fix] 사이드바 Review 데이터 버그 해소
  client/src/components/Common/ReviewContent/index.tsx
  client/src/components/Map/index.tsx
  client/src/components/Sidebar/index.tsx
  client/src/controllers/reviewController.ts
  client/src/pages/MainPage.tsx
Labels: Fix, FE, High

#138 [Fix] 사이드바 리뷰 버그 해소
  client/src/components/Common/ReviewContent/index.tsx
  client/src/components/Map/index.tsx
  client/src/components/Sidebar/index.tsx
  client/src/controllers/reviewController.ts
  client/src/pages/MainPage.tsx
Labels: Fix, BE, FE, High

#145 [Fix] Review 전달 시, Multi Query update transaction 적용
  server/src/api/reviewController.ts
  server/src/loaders/expressLoader.ts
  server/src/services/mapService.ts
  server/src/services/reviewService.ts
Labels: Fix, BE, High

#151 Fix/private route 라우팅 구조 수정
  client/src/App.tsx
  client/src/components/Common/Modal/index.tsx
  client/src/components/Header/index.tsx
  client/src/components/Profile/index.tsx
  client/src/components/ReviewModal/index.tsx
  client/src/components/SignUpModal/index.tsx
  client/src/components/Snackbar/index.tsx
  client/src/controllers/authController.ts
  client/src/controllers/reviewController.ts
  client/src/controllers/signInController.ts
  client/src/controllers/signUpController.ts
  client/src/hooks/useHistoryRouter.ts
  client/src/pages/LoadingPage.tsx
  client/src/pages/ProfileAddressPage.tsx
  client/src/utils/common.ts
  client/src/utils/useRouter.ts
Labels: Fix, FE, High

#146 Feat/validate image 프로필 이미지 UX 개선
  client/src/components/Header/index.style.tsx
  client/src/controllers/profileController.ts
  client/src/utils/common.ts
Labels: Fix, FE, Low

#143 Fix/hashtag 해시태그 예외 처리, 수정
  client/src/components/Sidebar/index.tsx
  client/src/controllers/reviewController.ts
  server/src/services/mapService.ts
  server/src/services/reviewService.ts
Labels: Fix, BE, FE, Middle

#148 Feat/polygon color 폴리곤 색상 겹치지 않도록 수정
  client/src/controllers/mapController.ts
Labels: Fix, FE, Middle

#152 [Feat] SWR을 사용한 폴리곤 캐싱 및 마커, 랭킹 커스텀 훅 정의
  client/package.json
  client/src/components/Map/index.tsx
  client/src/components/RankingModal/Selector/index.tsx
  client/src/components/RankingModal/index.tsx
  client/src/controllers/mapController.ts
  client/src/controllers/markerController.ts
  client/src/controllers/rankController.ts
  client/src/hooks/usePaths.ts
  client/src/hooks/useRanks.ts
  client/src/hooks/useRates.ts
  client/src/types/Map.d.ts
  client/src/utils/address.ts
  client/src/utils/common.ts
  client/yarn.lock
  server/src/api/indexController.ts
  server/src/api/mapController.ts
  server/src/api/rankController.ts
  server/src/services/index.ts
  server/src/services/mapService.ts
  server/src/services/rankService.ts
  server/src/utils/index.ts
Labels: Feat, BE, FE, Middle

#156 [Feat] 랭킹에 공동순위 적용
  client/src/components/RankingModal/index.tsx
  client/src/hooks/useRanks.ts
  client/src/types/Rank.d.ts
Labels: Feat, FE, Low

#155 [Feat] SWR 캐시에 Eviction Policy 적용
  client/src/hooks/cacheProvider.ts
  client/src/index.tsx
Labels: Feat, FE, Middle

#150 [Feat] 사이드바 내가 쓴 후기 기능 구현
  client/src/components/Common/ReviewContent/index.style.tsx
  client/src/components/Common/ReviewContent/index.tsx
  client/src/components/Map/index.tsx
  client/src/components/ReviewModal/index.tsx
  client/src/components/Sidebar/index.style.tsx
  client/src/components/Sidebar/index.tsx
  client/src/controllers/reviewController.ts
  client/src/controllers/sidebarController.ts
  client/src/pages/MainPage.tsx
  client/src/types/Review.d.ts
  client/src/utils/common.ts
  server/src/api/adminController.ts
  server/src/api/reviewController.ts
  server/src/models/Review.ts
  server/src/services/reviewService.ts
  server/src/types/Admin.d.ts
  server/src/types/Review.d.ts
  server/yarn.lock
Labels: Feat, BE, FE, High

#160 [Fix] 불 필요한 Intersection Observer 관찰 요소 수정
  client/src/components/Common/ReviewContent/index.tsx
Labels: Fix, FE, Low

#163 [Refactor] Lazy Loading 설정을 통한 초기 렌더링 최적화
  client/src/App.tsx
Labels: Refactor, FE, Middle

#171 [Refactor] for-of 문 Promise.all 리팩토링하여 병렬 처리
  server/src/services/reviewService.ts
Labels: Refactor, BE, Middle

#178 Feat/docker 도커 적용
  .env
  .github/workflows/main.yml
  client/.dockerignore
  client/Dockerfile.development
  client/Dockerfile.production
  client/package.json
  client/public/index.html
  client/yarn.lock
  docker-compose.yml
  nginx/Dockerfile.development
  nginx/Dockerfile.production
  nginx/development.conf
  nginx/production.conf
  nginx/tls/donggle-key.pem
  nginx/tls/donggle.pem
  server/.dockerignore
  server/Dockerfile.development
  server/Dockerfile.production
  server/package.json
  server/src/models/MapInfo.ts
Labels: Feat, Deploy, Middle

#175 [Feat] API 경계좌표 Cache-Control 헤더 추가
  client/src/hooks/cacheProvider.ts
  server/src/api/mapController.ts
Labels: Feat, BE, Middle

#188 [Feat] Reacat.memo 및 최적화 hooks를 사용한 프론트엔드 최적화
  client/package.json
  client/src/components/AddressModal/index.style.tsx
  client/src/components/AddressModal/index.tsx
  client/src/components/Common/Modal/index.style.tsx
  client/src/components/Common/Modal/index.tsx
  client/src/components/Header/index.style.tsx
  client/src/components/Header/index.tsx
  client/src/components/Map/index.style.tsx
  client/src/components/Map/index.tsx
  client/src/components/Profile/index.style.tsx
  client/src/components/Profile/index.tsx
  client/src/components/Searchbar/index.style.tsx
  client/src/components/Searchbar/index.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/ProfileAddressPage.tsx
  client/src/pages/ProfilePage.tsx
  client/yarn.lock
Labels: Feat, FE, Middle

#121 [Feat] Swagger API 적용
  server/package.json
  server/src/config/index.ts
  server/src/loaders/expressLoader.ts
  server/src/utils/swagger.json
  server/yarn.lock
Labels: Feat, BE, Low

#190 [Fix] docker 개발 환경 수정
  client/Dockerfile.development
  docker-compose.yml
  nginx/development.conf
  server/Dockerfile.development
  server/src/loaders/dbLoader.ts
Labels: Fix, Deploy, Middle

#191 [Fix] 전체 페이지 및 Modal UI 버그 해소 및 리팩토링
  client/src/App.tsx
  client/src/components/Common/Modal/index.style.tsx
  client/src/components/Header/index.tsx
  client/src/components/Searchbar/index.style.tsx
  client/src/controllers/sidebarController.ts
  client/src/modals/AddressModal/index.style.tsx
  client/src/modals/AddressModal/index.tsx
  client/src/modals/ProfileAddressModal/index.tsx
  client/src/modals/RankingModal/Rankbar/index.style.tsx
  client/src/modals/RankingModal/Rankbar/index.tsx
  client/src/modals/RankingModal/Selector/index.style.tsx
  client/src/modals/RankingModal/Selector/index.tsx
  client/src/modals/RankingModal/index.style.tsx
  client/src/modals/RankingModal/index.tsx
  client/src/modals/ReviewSubmitModal/alertStyle.css
  client/src/modals/ReviewSubmitModal/index.style.tsx
  client/src/modals/ReviewSubmitModal/index.tsx
  client/src/modals/SignInModal/index.style.tsx
  client/src/modals/SignInModal/index.tsx
  client/src/modals/SignUpModal/index.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/NotFoundPage.tsx
  client/src/pages/ProfilePage.tsx
  client/src/pages/RankingPage.tsx
  client/src/pages/ReviewPage.tsx
  client/src/pages/ReviewSubmitPage.tsx
  client/src/pages/SignInPage.tsx
  client/src/pages/SignUpPage.tsx
  client/src/pages/index.ts
  client/src/styledComponents/GlobalStyle.ts
  client/tsconfig.path.json
  client/yarn.lock
Labels: Fix, Refactor, FE, Middle

#193 [Refactor] Backend Error handling 리팩토링 진행
  server/src/api/adminController.ts
  server/src/apis/adminController.ts
  server/src/apis/authController.ts
  server/src/apis/indexController.ts
  server/src/apis/mapController.ts
  server/src/apis/reviewController.ts
  server/src/apis/userController.ts
  server/src/app.ts
  server/src/configs/index.ts
  server/src/configs/secretKey.ts
  server/src/loaders/dbLoader.ts
  server/src/loaders/expressLoader.ts
  server/src/loaders/loggerLoader.ts
  server/src/middlewares/auth.ts
  server/src/services/authService.ts
  server/src/services/jwtService.ts
  server/src/services/updateMapService.ts
  server/src/utils/authError.ts
  server/src/utils/error.ts
Labels: Fix, Refactor, BE, Middle
