Repository boostcampwm-2021/Web11-Donggle, pull requests merged in 2021-12, with the labels that each got.

#199 [Refactor] Loading Animation, Snack bar CSS 최적화
  client/src/components/Loading/index.style.tsx
  client/src/components/Snackbar/index.style.tsx
Labels: Refactor, FE, Low

#200 [Refactor] 에러처리, fetch 리팩토링
  client/src/components/Snackbar/index.style.tsx
  client/src/controllers/profileController.ts
  client/src/controllers/searchbarController.ts
Labels: Refactor, FE, Middle

#204 [Refactor] 폴리곤, 평점 에러핸들링 스낵바 적용 외
  client/src/components/Header/index.tsx
  client/src/components/Map/index.tsx
  client/src/controllers/mapController.ts
  client/src/controllers/markerController.ts
  client/src/hooks/usePaths.ts
  client/src/hooks/useRates.ts
  client/src/utils/common.ts
  nginx/tls/donggle-key.pem
  nginx/tls/donggle.pem
Labels: Fix, Refactor, FE

#205 [Refactor] ESLint warning 이슈 해소
  client/src/components/Snackbar/index.tsx
  client/src/controllers/authController.ts
  client/src/controllers/loadController.ts
  client/src/controllers/mapController.ts
  client/src/controllers/markerController.ts
  client/src/controllers/profileController.ts
  client/src/controllers/searchbarController.ts
  client/src/controllers/sidebarController.ts
  client/src/controllers/signInController.ts
  client/src/controllers/signUpController.ts
  client/src/hooks/useHistoryRouter.ts
  client/src/hooks/usePaths.ts
  client/src/hooks/useRanks.ts
  client/src/hooks/useRates.ts
  client/src/pages/LoadPage.tsx
  client/src/types/Common.d.ts
  client/src/utils/address.ts
  client/src/utils/common.ts
  server/src/apis/mapController.ts
Labels: Refactor, FE, Middle

#209 fix: #208 - 마커 아래 클릭 불가 공간이 생기는 이슈
  client/src/components/Map/markerStyle.css
  client/src/controllers/markerController.ts
Labels: Fix, FE, Middle

#210 [Refactor] Sidebar 후기 POST, GET 요청 관련 Snackbar 적용
  client/src/controllers/sidebarController.ts
  client/src/controllers/signInController.ts
  server/src/apis/reviewController.ts
Labels: Refactor, FE, Middle

#212 [Fix] 맵 스타일 수정
  client/src/components/Map/index.style.tsx
  client/src/components/Map/index.tsx
  client/src/components/Sidebar/index.style.tsx
  client/src/pages/MainPage.tsx
Labels: Fix, FE, Middle

#216 [Fix] 모달을 띄울 때 배경이 Suspense로 인해 재렌더링되는 이슈
  client/src/App.tsx
Labels: Fix, FE, Middle

#221 [Refactor] Swagger 적용 및 REST API 구조 변경
  client/src/components/Header/index.tsx
  client/src/controllers/profileController.ts
  client/src/controllers/searchbarController.ts
  client/src/hooks/cacheProvider.ts
  client/src/hooks/usePaths.ts
  server/src/apis/adminController.ts
  server/src/apis/authController.ts
  server/src/apis/mapController.ts
  server/src/apis/reviewController.ts
  server/src/apis/userController.ts
  server/src/utils/error.ts
  server/src/utils/swagger.json
Labels: Refactor, BE, FE, Middle

#225 [Fix] 프로필 페이지 버그 수정
  client/src/components/Header/index.tsx
  client/src/components/Profile/index.tsx
  client/src/components/Searchbar/index.tsx
  client/src/controllers/profileController.ts
  client/src/modals/ProfileAddressModal/index.tsx
  client/src/utils/common.ts
Labels: Fix, BE, FE, Middle

#228 [Fix] 마커 위에서 드래그했을 때 사이드바가 열리는 이슈
  client/src/components/Map/index.tsx
Labels: Fix, FE, Middle

#230 [Fix] Star, Bar Rate UI 버그 이슈 해소
  client/src/components/Common/BarRate/index.style.tsx
  client/src/components/Common/StarRate/index.style.tsx
Labels: Fix, FE, Low

#234 [Fix] 드롭다운 스타일 수정
  client/src/components/Searchbar/index.tsx
Labels: Fix, FE, Middle

#236 [Feat] 3개월 내 후기 재 제출 불가 로직 구현
  client/src/controllers/sidebarController.ts
  client/src/modals/ReviewSubmitModal/alertStyle.css
  server/src/apis/reviewController.ts
  server/src/services/reviewService.ts
Labels: Feat, BE, FE, Low

#240 [Refactor] Lighthouse 권고 사항 적용
  client/public/index.html
  client/src/components/Header/index.tsx
  client/src/components/Map/index.style.tsx
  client/src/components/Searchbar/index.style.tsx
  client/src/components/Searchbar/index.tsx
  nginx/production.conf
Labels: Fix, FE, Low

#243 [Fix] Image Webp로 변경, Label 제거, Meta description 추가
  client/public/index.html
  client/src/assets/images/logo.png
  client/src/assets/images/logo.webp
  client/src/components/Header/index.tsx
  client/src/components/Searchbar/index.tsx
Labels: Fix, FE, Low

#246 [Fix] 축척 비 재설정
  client/src/components/Map/index.tsx
  client/src/utils/address.ts
Labels: Fix, FE, Middle

#254 [Fix] dropdown 화면 넘침 수정
  client/src/components/Searchbar/index.tsx
Labels: Fix, FE, Middle

#257 [Test] Backend jest 기반 Map test 코드
  server/.babelrc
  server/package.json
  server/src/tests/dotenv/env.js
  server/src/tests/map.test.ts
  server/src/tests/simple.test.ts
  server/yarn.lock
Labels: Test, BE, Low
